### ISSUE TITLE
docker-compose file version

### ISSUE THREAD

**Issue by yucer** [Red5d/docker-autocompose#1]
This is a very useful tool.

Are there any plans to provide an option for the **Compose File** version ?

They have more versions now:

- [v1](https://docs.docker.com/compose/compose-file/compose-file-v1/)
- [v2](https://docs.docker.com/compose/compose-file/compose-file-v2/)
- [v3](https://docs.docker.com/compose/compose-file//)

**Comment by Red5d** [comment]
Yes, adding support for the updated compose file versions is definitely something I'd like to add when I have the time. Pull requests for implementing these are certainly welcome though :)

**Comment by edif30** [comment]
so how do you know which version this tool will put the compose file in?

**Comment by Red5d** [comment]
Right now it uses version 1. I'll see about adding support for v2/3 soon.

**Comment by edasque** [comment]
Any update on generating v3 versions?

**Comment by Red5d** [comment]
I've now updated the tool so it generates compose file v3 output by default. You can change it to v1 by giving the "-v 1" option before the container name/id(s).
