### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by SuperSpe** [Red5d/docker-autocompose#10]
```
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.nginx.networks.bridge contains null, which is an invalid type, it should be an array
services.portainer.networks.bridge contains null, which is an invalid type, it should be an array
services.grafana.labels.com.docker.compose.oneoff contains false, which is an invalid type, it should be a string, number,
or a null
services.influxdb.labels.com.docker.compose.oneoff contains false, which is an invalid type, it should be a string, number,
```
```
  nginx:
    networks:
      bridge:
        aliases:

```
Docker version 18.09.7, build 2d0083d

**Comment by jisakiel** [comment]
* I think it's emitting v2 files instead of v3? (at least my synology docker install complains about things like `cpu_shares` unless I edit that bit)
* I think it's mistaking the default bridge with *a* bridge. Meaning if I edit the yaml, and switch `networks: bridge: `for `network_mode: bridge` it works again.

**Comment by PonyOny** [comment]
Same here getting this output error.
`services.web-server-test.networks.bridge contains null, which is an invalid type, it should be an array`
and is caused due to.
```
networks:
  bridge:
    external: true
```

**Comment by Hukuma1** [comment]
Any fix for this besides manual editing? Seeing exactly the same 1 full year later. :/

> Same here getting this output error.
> `services.web-server-test.networks.bridge contains null, which is an invalid type, it should be an array`
> and is caused due to.
> 
> ```
> networks:
>   bridge:
>     external: true
> ```

**Comment by Red5d** [comment]
Thanks for the reminder, somehow I thought I'd resolved this. I'll try and sort this out today.

**Comment by akshaysalunke13** [comment]
@Red5d I've opened a [PR](https://github.com/Red5d/docker-autocompose/pull/14) solving this issue. Please have a look.

**Comment by Red5d** [comment]
Thanks! Merged.

**Comment by Hukuma1** [comment]
Trying to do a Jellyfin container export/import and running into it complaining about this:

```
    devices:
      - CgroupPermissions: rwm
        PathInContainer: /dev/dri
        PathOnHost: /dev/dri
```

Log:
```
Deployment error
The Compose file '/data/compose/51/docker-compose.yml' is invalid because: services.Jellyfin2.devices contains an invalid type, it should be a string
```

Any idea? This is strictly the code I am using from a running container and then re-importing it (with different container name) to launch a stack.

**Comment by Red5d** [comment]
Hmm... that should definitely be formatted like this instead according to the compose file documentation:

    devices:
      - /dev/dri:/dev/dri

I'll check and see if the "devices" section is different than others in the JSON or something.
https://docs.docker.com/compose/compose-file/compose-file-v3/#devices

**Comment by Hukuma1** [comment]
Any updates? It still says it. :/ Obviously can manually edit it for now, but others might not understand the failure if they run it.

**Comment by Red5d** [comment]
I've fixed the formatting on devices entries.
