### ISSUE TITLE
Support arm platforms?

### ISSUE THREAD

**Issue by fryfrog** [Red5d/docker-autocompose#15]
I support a variety of software which has a variety of Docker containers and your generator for running containers -> compose is absolutely invaluable in doing that, it makes support *so easy* having a common language to compare in and for surfacing all the tiny, hidden little things.

But it doesn't work on arm!

Would it be possible to support the various arm platforms? :)

**Comment by Red5d** [comment]
The python script itself should work on ARM as long as the dependencies are installed. I'm looking into getting the docker image automatically built for ARM too though.

**Comment by fryfrog** [comment]
You know, I probably should have just had a go at it and sent a PR. I bet it isn't too hard.

**Comment by LePremier** [comment]
Same issue here. Wanted to backup my stack running on the raspy 4. So arm support would be an awesome feature! :)

**Comment by Red5d** [comment]
@LePremier You can still use this python script by itself on ARM, it's just the docker image for it that isn't ARM-compatible yet. I haven't had time recently to get that sorted out yet.

**Comment by Red5d** [comment]
I've now merged @doob187 's PR and setup other Github Actions stuff to support that. I've also pulled the resulting image and verified that it works on a Raspberry Pi. I'm updating the README to point to the new Github Actions image builds too.
