### ISSUE TITLE
(Feature Request) Add option to generate compose file from all containers at once

### ISSUE THREAD

**Issue by CobaltGit** [Red5d/docker-autocompose#16]
I'm looking for a feature where you can generate one compose file from all your containers running at once, or would the following work?
```bash
docker ps -aq | xargs sudo python autocompose.py
```

**Comment by Red5d** [comment]
Yep, that should work. Generating an all-in-one compose file from multiple containers is already a feature. You can pipe the container names/ids in like that or list the ones you want directly like:

    sudo python autocompose.py container1 container2 container3

**Comment by CobaltGit** [comment]
Ah, that's good then. Thanks!
