### ISSUE TITLE
Impossible to run on a stoped container

### ISSUE THREAD

**Issue by P6g9YHK6** [Red5d/docker-autocompose#19]
As the title says if a container is not running the auto compose does not work it's for some container configuration impossible to achieve.

is it something that could be changed ?

**Comment by Red5d** [comment]
Sorry I missed this one. Try the latest version of the script and see if that fixes it. Various incorrect configuration issues have been addressed. If that doesn't work, what errors are you getting after that?

**Comment by Red5d** [comment]
Re-read this and realized you were trying to run on a stopped container, sorry. It was late when I read this previously. I think when originally writing this, I assumed people wouldn't need to run on a stopped container or wouldn't be able to run it. I've addressed and verified that this works as of the latest commit.

Try the latest image with these updates:

`docker pull ghcr.io/red5d/docker-autocompose:latest`

**Comment by ThinkPadNL** [comment]
Hi @Red5d 
It seems that the fix you did in Aug. 2021 is not in the Docker image 'latest'.

    $ sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock red5d/docker-autocompose -v 3 d9135ba4a701
    That container is not running.
Would it be possible to update the Docker image with the latest GitHub version of the tool?
