### ISSUE TITLE
The default network adapter "bridge" breaks docker-compose

### ISSUE THREAD

**Issue by P8ntBal1551** [Red5d/docker-autocompose#20]
When I try to import the docker-compose file (after I fix the volume not defined error) it comes back with

"ERROR: for Dokuwiki  network-scoped alias is supported only for containers in user defined networks

ERROR: for Dokuwiki  network-scoped alias is supported only for containers in user defined networks
ERROR: Encountered errors while bringing up the project."

to fix it, I can change

    networks:
      - bridge

to

    network_mode: bridge

I know that I'm actually changing the context of the file to say "just bridge my connection" instead of "join the bridge network", but that's all I need for my containers

thank you

**Comment by Red5d** [comment]
I've now fixed this to not include the "networks" key if only the bridge network is present.
