### ISSUE TITLE
Create auto-build on DockerHub

### ISSUE THREAD

**Issue by schmunk42** [Red5d/docker-autocompose#3]
Neat tool! Would be nice to have an automated build on DockerHub.

**Comment by Red5d** [comment]
Done! https://hub.docker.com/r/red5d/docker-autocompose/

**Comment by phit42** [comment]
Quick question: does that mean that the Container image in the DockerHub registry contains the latest bugfixes as well as it pulls from here, or is the github ghcr.io to be used instead?
