### ISSUE TITLE
unable to start container from yml file

### ISSUE THREAD

**Issue by Mio3000** [Red5d/docker-autocompose#31]
when im trying to start container from exported yml file, im receiving following error message:
`root@openmediavault:~/smokeping# docker-compose up -d
ERROR: Invalid interpolation format for "environment" option in service "smokeping": "PS1=$(whoami)@$(hostname):$(pwd)\$ "
`

the environment looks like this:
version: "3"
services:
  smokeping:
    container_name: smokeping
    entrypoint:
      - /init
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Bratislava
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - 'PS1=$(whoami)@$(hostname):$(pwd)\$ '
      - HOME=/root
      - TERM=xterm
    hostname: 442d8cca9031

**Comment by Red5d** [comment]
Looks like you might need 2 $ signs: https://docs.docker.com/compose/environment-variables/#the-env-file

You wouldn't normally need to set a PS1 variable for a docker container since most of the time you won't be using the cli inside the container, so you could also just delete that line.
