### ISSUE TITLE
/var/run/docker.sock - docker compose issue

### ISSUE THREAD

**Issue by shuther** [Red5d/docker-autocompose#44]
docker-autocompose generates a docker-compose.yml that returns an error for docker compose (2.9.0)
```
volumes:
  /var/run/docker.sock:
    external: true
```
Removing the 3 lines above from docker-compose.yml fix the issue.

**Comment by acdoussan** [comment]
probably fixed with the latest commit, could you try that?

If not, please add the output of `docker inspect <container name>`
