### ISSUE TITLE
date_or_time syntax error?

### ISSUE THREAD

**Issue by CDarwin7** [Red5d/docker-autocompose#49]
I am getting this error when running sudo python autocompose.py any container  

File "autocompose.py", line 42
    def is_date_or_time(s: str):
                         ^
SyntaxError: invalid syntax

Docker Info 
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., 2.10.2)

Server:
 Containers: 24
  Running: 16
  Paused: 0
  Stopped: 8
 Images: 53
 Server Version: 20.10.17-ce
 Storage Driver: btrfs
  Build Version: Btrfs v5.18.1
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux oci runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.4-0-ga916309fff0f
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.19.7-1-default
 Operating System: openSUSE Tumbleweed
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.13GiB
 Name: caesar
 ID: Y52M:FTLU:T5JM:7RZL:YU3H:QKIG:LLUC:P3M6:JCQQ:HVLX:KFEM:AWCQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by yeyeto2788** [comment]
Hey @CDarwin7,

Can you try this https://github.com/Red5d/docker-autocompose/pull/53? The issue should be gone.
