### ISSUE TITLE
Error running this from Docker

### ISSUE THREAD

**Issue by tehniemer** [Red5d/docker-autocompose#5]
I've created a container and try to run this but get the error 

```
usage: autocompose.py [-h] cname
autocompose.py: error: the following arguments are required: cname
```

My input parameter was

```
docker run -v /var/run/docker.sock:/var/run/docker.sock red5d/docker-autocompose $ombi
```

**Comment by Red5d** [comment]
Are you sure the $ombi variable actually contained a text value? That looks like it should have worked.

**Comment by tehniemer** [comment]
'''ombi''' is the name of the container, should I use the container ID instead?

**Comment by Red5d** [comment]
The container name is the right one to use, but by putting that "$" in front of the name, it became an empty variable called "$ombi". Try running it like this:

    docker run -v /var/run/docker.sock:/var/run/docker.sock red5d/docker-autocompose ombi

**Comment by Red5d** [comment]
Ah, I see where you got that from the example in the Readme. I suppose that format is a bit confusing. I'll fix that.

**Comment by tehniemer** [comment]
Sweet, that did the trick, thanks for the help.
