### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by billouetaudrey** [Red5d/docker-autocompose#52]
Hello, I have an issue when I want print all container : 

`billou@billou-serveur:~/Téléchargements/Serveur/docker-autocompose$ sudo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/red5d/docker-autocompose $(docker ps -aq)
Traceback (most recent call last):
  File "/usr/src/app/./autocompose.py", line 211, in <module>
    main()
  File "/usr/src/app/./autocompose.py", line 29, in main
    cfile, c_networks, c_volumes = generate(cname, createvolumes=args.createvolumes)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/./autocompose.py", line 140, in generate
    assumed_default_network = list(cattrs['NetworkSettings']['Networks'].keys())[0]
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
`

Any idea please?

**Comment by yeyeto2788** [comment]
Hey @billouetaudrey 

Can you try this https://github.com/Red5d/docker-autocompose/pull/53?
