### ISSUE TITLE
Best way to send output to a file?

### ISSUE THREAD

**Issue by jtjh** [Red5d/docker-autocompose#55]
Just been tinkering with this, obv can't just append tee or > to the end of the docker command and something like |& > output.txt does not work.

What is the best option here?

**Comment by dhumphrey7** [comment]
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/red5d/docker-autocompose container _name > container_name.yml worked for me.  Since the run command just outputs the results to the screen you are able to append that to a file.

**Comment by Red5d** [comment]
As @dhumphrey7 mentioned, appending "> container_name.yml" to the end of the docker run command does actually work and is the best way to output directly to a file.
