### ISSUE TITLE
Boolean value should be true/false ?

### ISSUE THREAD

**Issue by windsurf** [Red5d/docker-autocompose#61]
Get an error like "failed to deploy a stack: <name> must be a boolean or mapping "

In this case an network was made "external: yes", which should be "external:true", the latter works OK
 
Odroid N2+, Linux 5.15.0-odroid-arm64, Portainer CE 2.18.3,

**Comment by Pr0dt0s** [comment]
I'm having the ame problem here, I'll try to submit a PR with the fix.
