### ISSUE TITLE
That container is not available

### ISSUE THREAD

**Issue by emawata** [Red5d/docker-autocompose#64]
Hi, What version of python do you need to run correctly? I receive the following error.
  
```
  File "autocompose.py", line 148
    print("That container is not available.", file=sys.stderr)
                                                  ^
SyntaxError: invalid syntax
```

I use Python 3.8.10 in Ubuntu 20.04.

Any helps?

**Comment by Red5d** [comment]
Are you sure it's actually being executed with python3 and not 2? Sometimes the default for the "python" command is 2 and "python3" needs to be specified. That syntax is definitely valid for python 3.x
