### ISSUE TITLE
Block of volumes in random order  (mountpoints)

### ISSUE THREAD

**Issue by dallben** [Red5d/docker-autocompose#65]
I regularly run the program and send the output to git, and I get too many version changes only because the order of the volumes appears randomly, I think that just adding **.sort()** on line 250 would be the solution to my problem leaving it as: 

`values["volumes"] = mountpoints.sort() `

<img width="899" alt="image" src="https://github.com/Red5d/docker-autocompose/assets/28881580/635a8ef9-f0e1-4bf9-af86-3a24a508b4f9">

<img width="940" alt="image" src="https://github.com/Red5d/docker-autocompose/assets/28881580/a334764f-96ff-46f4-ba0a-7bdc2e0af818">

**Comment by Red5d** [comment]
Added in [latest commit](https://github.com/Red5d/docker-autocompose/commit/e1c0e23ff2a39022fbecb610e3efcee06a4f1ce7)

**Comment by dallben** [comment]
Bravo, genius! You've aced it!
