### ISSUE TITLE
Documentation - container id vs container name

### ISSUE THREAD

**Issue by reggiepierce** [Red5d/docker-autocompose#7]
The documentation says to use:
docker run -v /var/run/docker.sock:/var/run/docker.sock red5d/docker-autocompose <container-id>

However, that always failed with:
That container is not running.

The following does work:
docker run -v /var/run/docker.sock:/var/run/docker.sock red5d/docker-autocompose <container-name>

I would suggest updating the docs. Bonus points for updating your code to accept a name OR id.

**Comment by Red5d** [comment]
Those two commands you mentioned look the same to me, though they're both missing a container name/id. I've now updated the tool to take a list of either container names or ids as input. See the updated README page.
