### ISSUE TITLE
Introduce PEP518 for support of Python 3.12

### ISSUE THREAD

**Issue by Galaxy102** [Red5d/docker-autocompose#78]
Hello and thanks for your ongoing work on docker-autocompose.

When developing #77 I've found that the container image can no longer be built because Python deprecated the setup.py method for building in 3.12.

If you like I can create a PR introducing PEP518 compatibility.
For this, some decisions must be made.

### Build System
See https://packaging.python.org/en/latest/tutorials/packaging-projects/#choosing-a-build-backend

I'd prefer going with [Poetry](https://python-poetry.org/) as it is widely spread and I'm quite comfortable with it. 

### Dependencies
The dependencies have not been updated in a long time. May I update them?

### Minimum supported Python version
PEP518 wants the minimum required Python version to be set. If going with Poetry, this must be at least 3.8 (this is the case in Ubuntu Focal, the oldest still supported LTS). This might be a rather cosmetical choice as I'd think most folks use the container image for running docker-autocompose.

---
Please let me know of your thoughts.

**Comment by Red5d** [comment]
Sure, if you're willing to create the PR to address that, then that'd be appreciated! I've also reviewed and merged #77 , thanks!
