### ISSUE TITLE
Multiple networks and alias

### ISSUE THREAD

**Issue by wassy92x** [Red5d/docker-autocompose#8]
I have a container that is attached to two networks: dockerNet and dockerNetv6 (dockerNet is set as the default network of this container). The container has also some aliases.
Unfortunately the tool ignores multiple networks and aliases.

**Comment by Red5d** [comment]
Just added the code to support networks and aliases. It works for some containers with attached networks that I tested. Let me know if it works properly for you.

**Comment by wassy92x** [comment]
Thank you for your efforts  :)
It works now.
