### ISSUE TITLE
Dependency versions?

### ISSUE THREAD

**Issue by FacePalmDev** [Red5d/docker-autocompose#9]
So I've been trying to get this working. I think you need to supply your dependency versions? You could try doing a pip list or pip freeze? I'm planning to give you a pull request with a requirements file so that you can just install dependencies with 1 command (and other people won't run into this problem).

**Comment by Red5d** [comment]
What kind of errors are you getting?

**Comment by KiransHub** [comment]
```PS D:\Repos\docker-autocompose> python autocompose.py 324733d43248 c3cb064f48de 94e795301c19
Traceback (most recent call last):
  File "autocompose.py", line 126, in <module>
    main()
  File "autocompose.py", line 15, in main
    cfile, networks = generate(cname)
  File "autocompose.py", line 33, in generate
    cid = [x.short_id for x in c.containers.list() if cname == x.name or x.short_id in cname][0]
AttributeError: 'function' object has no attribute 'list'```

**Comment by Red5d** [comment]
Hmm... what version of the "docker" python module do you have?

**Comment by bpjobin** [comment]
I was getting the same error. Fixed it by installing docker 2.1.0 as described here: https://github.com/docker/docker-py/issues/2177

`pip install docker==2.1.0`

**Comment by KiransHub** [comment]
I didn't know you could install docker via pip?

**Comment by Red5d** [comment]
Its not Docker itself. Installing "docker" with pip installs the docker Python module.

**Comment by phil-hudson** [comment]
Should this be PR'ed into a requirements.txt file?

**Comment by phil-hudson** [comment]
https://github.com/Red5d/docker-autocompose/pull/11
